import mongoose from "mongoose";

const schemaProdutos = new mongoose.Schema({
    nome:{
        type:String,
        required:true,
        trim:true,
        maxLength:70
    },
    tecido:{
        type:String,
        required:true,
        trim:true,
        maxLength:70
    },
    estampa:{
        type:String,
        required:true,
        trim:true,
        maxLength:70
    }, 
    quantidade:{
        type:Number,
        require:true
    },
    tamanho:{
        type:String,
        require:true,
        maxLength:1,
        minLength:1
    },
    cor:{
        type:String,
        require:true,
        maxLength:70
    },
    preco:{
        type:Number,
        require:true
    },
    custo:{
        type:Number,
        require:true
    },
    fornecedor:{
        type:mongoose.ObjectId,
        ref:"Fornecedores",
        require:true
    },
    marca:{
        type:String,
        require:true,
        maxLength:70
    },
    imgFrente:{
        data:Buffer,
        contentType:String
    },
    imgTras:{
        data:Buffer,
        contentType:String
    },
    imgCorpo:{
        data:Buffer,
        contentType:String
    }
}, {timestamps:true});

export default mongoose.model("Produtos", schemaProdutos)